### PR TITLE
WIP: Creating tests

### PR DESCRIPTION
**Pull request by PuZZleDucK**
This is a WIP to discuss issues I have had and check if I'm heading in the right direction.

There is only one test at the moment which creates a relation between a person and a pet as the README.md documentation demonstrates. Unfortunately I had to make a few unexpected changes to get the test to run and pass. I wanted to see if there was something I'm doing wrong or if the documentation might be out of date (in which case I could update it).

The example I have tried to replicate in this test is the first one from the document
```
@pet.person = @person
```
However this failed to run (with: "undefined method `person=' for #<Pet...") and I could only get the expected result by directly manipulating the ids
```
@pet.person_id = @person.id
```

Another small, but unexpected change was having to replace `require 'UUID'` with `require 'uuid'`. I wasn't able to find anything to indicate what version of Ruby or any of the gems should be and maybe I have the wrong gem/version/ruby installed?

### CODE REVIEW

**Comment by ricvillagrana** [comment]
@PuZZleDucK thanks for the PR.
Yes, this kind of assignment is not supported (yet), is an issue (#9):
```ruby
@pet.person = @person
```

You can use the ids assignment to get this done, this test is going to be updated on the PR that solves that issue in the future.

The `uuid` problem is a bit strange, I get it working in 2.6.5 with the gem [`uuid (2.3.9)`](https://rubygems.org/gems/uuid). (I didn't need to update the code)

**Comment by ricvillagrana** [comment]
@PuZZleDucK are you still willing to merge this PR? If so, just finish it and I'll merge it as soon as you remove the `WIP`. Thanks for your contribution, I really appreciate it. :smile:
